# Generated by Django 5.1 on 2024-08-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0004_alter_view_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
