# Generated by Django 5.1 on 2024-08-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
