# Generated by Django 5.1 on 2024-09-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
